### ISSUE TITLE
User partial view not showing

### ISSUE THREAD

**Issue by trollfalgar** [stephenlake/nova-snowball#4]
Hello, I installed this package but the top right user view is not showing. I reinstalled it, and it still doesn't work.

Laravel: 6.16
Nova: 2.11.1
Snowball: 1.2.7

Thanks.

**Comment by stephenlake** [comment]
https://github.com/cloudcake/nova-fixed-bars/issues/7

Feel free to re-open if that doesn't solve your issue or submit a PR fix.
