### ISSUE TITLE
Floating / always visible buttons

### ISSUE THREAD

**Issue by gabrieltakacs** [stephenlake/nova-snowball#5]
As some forms can be really long when filling them on mobile / tablet and users might need to save the form continuously, it would be very nice to have floating / always visible buttons (those that are standardly displayed only in the bottom of the page: Cancel / Update & Continue editing, Update). Would it be possible to add something like that?

**Comment by stephenlake** [comment]
> Would it be possible to add something like that?

PR's are welcome.
