### ISSUE TITLE
Logged User Menu disappeared

### ISSUE THREAD

**Issue by ahaneef29** [stephenlake/nova-snowball#6]
After installing this theme,  I can't able to logout. There is no menu on the top right side. ?

**Comment by dataxlamsterdam** [comment]
Same problem here, on config 'sidebarSize' => 'thin' it shows up a little bit (24 inch screen) and by setting normal it is gone.
I will fix it one these days and make a pull request.
Or did you fix it and can you share it with me @ahaneef29

**Comment by stephenlake** [comment]
Feel free to submit a PR fix.

**Comment by dataxlamsterdam** [comment]
It seems the class: 'dropdown-right' doesn't exist anymore in CSS and Nova make some resposive by the default stylesheets.
Quick solution for now:

.dropdown-right { position: fixed; right: 0; padding-right: 30px; } 

This will fix the problem on Desktop and fix also the mobile problem (little padding added on right in mobile).

**Comment by stephenlake** [comment]
Merged in and released under [v1.2.8](https://github.com/cloudcake/nova-snowball/releases/tag/v1.2.8)
